### ISSUE TITLE
Automatically generate documentation from existing metadata

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/malc#7]
This issue stems from a conversation regarding the documentation efforts in coreLang, which can be found [here](https://github.com/mal-lang/coreLang/issues/48).

The general idea would be to have the malcompiler generate the rst([reStructuredText](https://docutils.sourceforge.io/rst.html)) file that can then be augmented and plugged into [Sphinx](https://www.sphinx-doc.org/en/master/#).

The reason for having it in the compiler is that it already contains a parser and can therefore more easily generate the rst files. This would also mean that the support for automatically generated documentation would be available to all MAL languages.

**Comment by maxwalls** [comment]
I suggest creating a separate tool for this. This compiler outputs a `.mar` file that contains all information about a language, including info strings. This output file can be opened with the library https://github.com/mal-lang/mal-langspec for programmatic access to all information, and it can be opened manually since it is a ZIP archive that contains a JSON file describing every aspect of a language. This makes it easier to create separate tools that integrate with a MAL language, and I think generating documentation would best be done this way.
